
######################################################
#
# Configuracao do Inicializador de Threads task-executo
#
#
#
#####################################################
task-executor:
    core-pool-size: 10
    max-pool-size: 100
    queue-capacity: 100

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        
        
version: "2.1"

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
#    networks:
#      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
      KAFKA_MANAGER_LOGLEVEL: 60s
#  kafka_manager:
#    image: "mzagar/kafka-manager-docker:1.3.3.4"
#    container_name: kafkamanager
##    networks:
##      - kafkanet
#    ports:
#      - 9000:9000
#    links:
#      - kafkaserver
#    environment:
#      ZK_HOSTS: "kafkaserver:2181"
      
      
      
    kafka-manager:
      image: sheepkiller/kafka-manager:latest
      ports:
        - "9000:9000"
      links:
        - kafkanet
      environment:
        ZK_HOSTS: kafkaserver:2181
        APPLICATION_SECRET: letmein
        KM_ARGS: -Djava.net.preferIPv4Stack=true

